CREATE PROCEDURE [dbo].[SP_INS_CLIENTES]
	@PV_CEDULA VARCHAR (20),
	@PV_NOMBRES VARCHAR (100)
AS
BEGIN
	INSERT INTO CLIENTES(CEDULA,NOMBRE,ESTADO)
	VALUES(@PV_CEDULA,@PV_NOMBRES,'A');
END

go

CREATE PROCEDURE [dbo].[SP_UPD_CLIENTES]
	@PV_CEDULA VARCHAR (20),
	@PV_NOMBRES VARCHAR (100)
AS
BEGIN
	UPDATE CLIENTES
	SET NOMBRE=@PV_NOMBRES
	WHERE CEDULA=@PV_CEDULA
END

go

CREATE PROCEDURE [dbo].[SP_GET_CLIENTE]
	@PV_CEDULA VARCHAR (20)
AS
BEGIN
	SELECT * FROM CLIENTES
	WHERE CEDULA=@PV_CEDULA
END

go

CREATE PROCEDURE [dbo].[SP_GET_CLIENTES]
AS
BEGIN
	SELECT * FROM CLIENTES
END

go

CREATE PROCEDURE [dbo].[SP_DEL_CLIENTES]
	@PV_CEDULA VARCHAR (20)
AS
BEGIN
	UPDATE CLIENTES
	SET ESTADO='I'
	WHERE CEDULA=@PV_CEDULA
END