CREATE PROCEDURE [dbo].[SP_GET_PRODUCTOS]
AS
BEGIN
	SELECT * FROM PRODUCTOS
END

go

CREATE PROCEDURE [dbo].[SP_GET_PRODUCTO]
	@PV_CODIGO VARCHAR (20)
AS
BEGIN
	SELECT * FROM PRODUCTOS
	WHERE CODIGO=@PV_CODIGO
END

go

CREATE PROCEDURE [dbo].[SP_INS_PRODUCTOS]
	@PV_CODIGO VARCHAR (20),
	@PV_DESCRIPCION VARCHAR (100),
	@PF_PRECIO DECIMAL(10,2)
AS
	DECLARE @CONTADOR_ID INTEGER;
BEGIN
	SELECT @CONTADOR_ID=ISNULL(MAX(ID_PRODUCTO),0)+1
	FROM PRODUCTOS;

	INSERT INTO PRODUCTOS(ID_PRODUCTO,CODIGO,DESCRIPCION,PRECIO,ESTADO)
	VALUES(@CONTADOR_ID,@PV_CODIGO,@PV_DESCRIPCION,@PF_PRECIO,'A');
END

go

CREATE PROCEDURE [dbo].[SP_UPD_PRODUCTOS]
	@PV_CODIGO VARCHAR (20),
	@PV_DESCRIPCION VARCHAR (100),
	@PF_PRECIO DECIMAL(10,2)
AS
BEGIN
	UPDATE PRODUCTOS
	SET DESCRIPCION=@PV_DESCRIPCION,
		PRECIO=@PF_PRECIO
	WHERE
		CODIGO=@PV_CODIGO
END

go


CREATE PROCEDURE [dbo].[SP_DEL_PRODUCTOS]
	@PV_CODIGO VARCHAR (20)
AS
BEGIN
	UPDATE PRODUCTOS
	SET ESTADO = 'I'
	WHERE
		CODIGO=@PV_CODIGO
END