CREATE TABLE CLIENTES(
CEDULA VARCHAR(15),
NOMBRE VARCHAR(100),
ESTADO VARCHAR(1),
PRIMARY KEY (CEDULA)
)

CREATE TABLE PRODUCTOS(
ID_PRODUCTO INTEGER,
CODIGO VARCHAR(10) UNIQUE,
DESCRIPCION VARCHAR(100),
PRECIO DECIMAL(10,2),
ESTADO VARCHAR(1),
PRIMARY KEY (ID_PRODUCTO)
)


CREATE TABLE PROMOCIONES(
ID_PROMOCION INTEGER,
DESCRIPCION VARCHAR(100),
FECHA_INICIO DATETIME,
FECHA_FIN DATETIME,
ESTADO VARCHAR(1),
PRIMARY KEY (ID_PROMOCION)
)

CREATE TABLE PROMOCIONES_CLIENTES(
ID INTEGER,
ID_PROMOCION INTEGER,
CEDULA VARCHAR(15),
MONTO_DESCUENTO DECIMAL(10,2),
ESTADO VARCHAR(1),
PRIMARY KEY(ID),
FOREIGN KEY (ID_PROMOCION) REFERENCES PROMOCIONES(ID_PROMOCION),
FOREIGN KEY (CEDULA) REFERENCES CLIENTES(CEDULA)
)


CREATE TABLE PROMOCIONES_PRODUCTO(
ID INTEGER,
ID_PROMOCION INTEGER,
ID_PRODUCTO INTEGER,
MONTO_DESCUENTO DECIMAL(10,2),
ESTADO VARCHAR(1),
PRIMARY KEY(ID),
FOREIGN KEY (ID_PROMOCION) REFERENCES PROMOCIONES(ID_PROMOCION),
FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO)
)